<?php /*a:3:{s:62:"/Users/zhangboshuai/www/yiside/app/wechat/view/fans/index.html";i:1602740831;s:73:"/Users/zhangboshuai/www/yiside/app/wechat/view/../../admin/view/main.html";i:1603101865;s:69:"/Users/zhangboshuai/www/yiside/app/wechat/view/fans/index_search.html";i:1602740831;}*/ ?>
<div class="layui-card layui-bg-gray"><?php if(!(empty($title) || (($title instanceof \think\Collection || $title instanceof \think\Paginator ) && $title->isEmpty()))): ?><div class="layui-card-header notselect"><span class="layui-icon layui-icon-next font-s10 color-desc margin-right-5"></span><?php echo htmlentities((isset($title) && ($title !== '')?$title:'')); ?>111
        <div class="pull-right"><?php if(auth("black_add")): ?><button data-action='<?php echo url("black_add"); ?>' data-rule="openid#{key}" data-csrf="<?php echo systoken('black_add'); ?>" class='layui-btn layui-btn-sm layui-btn-primary'>拉入黑名单</button><?php endif; if(auth("black_del")): ?><button data-action='<?php echo url("black_del"); ?>' data-rule="openid#{key}" data-csrf="<?php echo systoken('black_del'); ?>" class='layui-btn layui-btn-sm layui-btn-primary'>移出黑名单</button><?php endif; if(auth("sync")): ?><button data-queue='<?php echo url("sync"); ?>' data-confirm="是否要创建后台任务同步用户数据？" class='layui-btn layui-btn-sm layui-btn-primary'>同步用户数据</button><?php endif; ?></div></div><?php endif; ?><div class="layui-card-body"><div class="think-box-shadow table-block"><fieldset><legend>条件搜索</legend><form class="layui-form layui-form-pane form-search" action="<?php echo request()->url(); ?>" onsubmit="return false" method="get" autocomplete="off"><div class="layui-form-item layui-inline"><label class="layui-form-label">微信昵称</label><label class="layui-input-inline"><input name="nickname" value="<?php echo input('nickname'); ?>" placeholder="请输入微信昵称" class="layui-input"></label></div><div class="layui-form-item layui-inline"><label class="layui-form-label">关注状态</label><label class="layui-input-inline"><select class="layui-select" name="subscribe"><?php foreach([''=>'-- 全部 --','0'=>'显示未关注的粉丝','1'=>'显示已关注的粉丝'] as $k=>$v): if($k.'' == input('subscribe')): ?><option selected value="<?php echo htmlentities($k); ?>"><?php echo htmlentities($v); ?></option><?php else: ?><option value="<?php echo htmlentities($k); ?>"><?php echo htmlentities($v); ?></option><?php endif; ?><?php endforeach; ?></select></label></div><div class="layui-form-item layui-inline"><label class="layui-form-label">拉黑状态</label><label class="layui-input-inline"><select class="layui-select" name="is_black"><?php foreach([''=>'-- 全部 --','0'=>'显示未拉黑的粉丝','1'=>'显示已拉黑的粉丝'] as $k=>$v): if($k.'' == input('is_black')): ?><option selected value="<?php echo htmlentities($k); ?>"><?php echo htmlentities($v); ?></option><?php else: ?><option value="<?php echo htmlentities($k); ?>"><?php echo htmlentities($v); ?></option><?php endif; ?><?php endforeach; ?></select></label></div><div class="layui-form-item layui-inline"><label class="layui-form-label">关注时间</label><label class="layui-input-inline"><input data-date-range name="subscribe_at" value="<?php echo input('subscribe_at'); ?>" placeholder="请选择关注时间" class="layui-input"></label></div><div class="layui-form-item layui-inline"><button type="submit" class="layui-btn layui-btn-primary"><i class="layui-icon">&#xe615;</i> 搜 索</button><button type="button" data-form-export="<?php echo url('index'); ?>?type=<?php echo htmlentities((isset($type) && ($type !== '')?$type:'')); ?>" class="layui-btn layui-btn-primary"><i class="layui-icon layui-icon-export"></i> 导 出
            </button></div></form></fieldset><script>
    window.form.render();
    require(['excel'], function (excel) {
        excel.bind(function (data, sexs) {
            sexs = {1: '男', 2: '女'};
            data.forEach(function (item, index) {
                data[index] = [
                    item.openid || '',
                    item.nickname || '',
                    item.country || '',
                    item.province || '',
                    item.city || '',
                    sexs[item.sex] || '未知',
                    item.subscribe ? '已订阅' : '未订阅',
                    item.subscribe_at || '',
                    item.is_black ? '已拉黑' : '未拉黑',
                ];
            });
            data.unshift(['OPENID', '微信昵称', '所在国家', '所在省份', '所在城市', '性别', '订阅状态', '订阅时间', '是否拉黑']);
            return data;
        }, '微信粉丝数据');
    });
</script><table class="layui-table margin-top-10" lay-skin="line"><?php if(!(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty()))): ?><thead><tr><th class='list-table-check-td think-checkbox'><label><input data-auto-none data-check-target='.list-check-box' type='checkbox'></label></th><th width="180px" class='text-left nowrap'>微信昵称</th><th width="180px"></th><th width="150px" class='text-left nowrap'>性别语言</th><th width="180px" class='text-left nowrap'>关注时间</th><th width="80px"></th><th></th></tr></thead><?php endif; ?><tbody><?php foreach($list as $key=>$vo): ?><tr><td class='list-table-check-td think-checkbox'><label><input class="list-check-box" value='<?php echo htmlentities($vo['openid']); ?>' type='checkbox'></label></td><td class='text-left nowrap'><div class="headimg" data-tips-image data-lazy-src="<?php echo htmlentities((isset($vo['headimgurl']) && ($vo['headimgurl'] !== '')?$vo['headimgurl']:'')); ?>"></div><div class="inline-block"><p>昵称：<?php echo htmlentities((isset($vo['nickname']) && ($vo['nickname'] !== '')?$vo['nickname']:'--')); ?></p><p>区域：<?php echo htmlentities((isset($vo['country']) && ($vo['country'] !== '')?$vo['country']:'--')); ?><?php echo htmlentities((isset($vo['province']) && ($vo['province'] !== '')?$vo['province']:'')); ?><?php echo htmlentities((isset($vo['city']) && ($vo['city'] !== '')?$vo['city']:'')); ?></p></div></td><td class="text-left padding-0"><div style="max-height:60px;overflow:auto"><?php foreach($vo['tags'] as $t): ?><p><span class="layui-badge layui-bg-cyan margin-right-5"><?php echo htmlentities((isset($t) && ($t !== '')?$t:'--')); ?></span></p><?php endforeach; ?></div></td><td class='text-left nowrap'>
                性别：<?php switch($vo['sex']): case "1": ?>男<?php break; case "2": ?>女<?php break; default: ?>未知<?php endswitch; ?><br>
                语言：<?php echo $vo['language']; ?></td><td class='text-left nowrap'>
                日期：<?php echo str_replace(' ','<br>时间：',format_datetime($vo['subscribe_at'])); ?></td><td class='text-center nowrap'><?php if($vo['subscribe'] == '0'): ?><span class="layui-badge">未关注</span><?php else: ?><span class="layui-badge layui-bg-green">已关注</span><?php endif; ?><br><?php if($vo['is_black'] == '0'): ?><span class="layui-badge layui-bg-green">未拉黑</span><?php else: ?><span class="layui-badge">已拉黑</span><?php endif; ?></td><td class="nowrap"><?php if(auth('black_add') and $vo['is_black'] == 0): ?><a class="layui-btn layui-btn-sm" data-action="<?php echo url('black_add'); ?>" data-value="openid#<?php echo htmlentities($vo['openid']); ?>" data-csrf="<?php echo systoken('black_add'); ?>">拉 黑</a><?php endif; if(auth('black_del') and $vo['is_black'] == 1): ?><a class="layui-btn layui-btn-sm" data-action="<?php echo url('black_del'); ?>" data-value="openid#<?php echo htmlentities($vo['openid']); ?>" data-csrf="<?php echo systoken('black_del'); ?>">移 出</a><?php endif; if(auth("remove")): ?><a class="layui-btn layui-btn-sm layui-btn-danger" data-action="<?php echo url('remove'); ?>" data-value="id#<?php echo htmlentities($vo['id']); ?>" data-csrf="<?php echo systoken('remove'); ?>" data-confirm="确定要删除该用户吗？">删 除</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><?php if(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty())): ?><span class="notdata">没有记录哦</span><?php else: ?><?php echo (isset($pagehtml) && ($pagehtml !== '')?$pagehtml:''); ?><?php endif; ?></div></div></div>